### PR TITLE
Reference the typings file in package.json; ignore methods from the new lifecycle API

### PR DESCRIPTION
**Pull request by code-hunger**
I expected the new commit to appear bellow the comments in #6 but it didn't. And so that the PR isn't too small, I added the methods from the new React API: https://reactjs.org/docs/react-component.html to the ignore list.

I don't want to mess up your version management, feel free to commit in this PR to change it if you want.

### CODE REVIEW

**Comment by zackargyle** [comment]
Hey! I pushed out `@1.3.1` just now. The problem was that the typescript file was not in the /src directory which is required because of the "files" key in package. Can you update this PR to point to the new location of the typescript file? `src/index.d.ts`

**Comment by code-hunger** [comment]
Done! I also rebased onto upstream because initially I made the mistake to pull upstream into patch-1, which caused a merge commit. I wanted to avoid it so I rebased, before realizing I don't need to. Anyway, it's clean now, and should work.

**Comment by zackargyle** [comment]
Perfect. Thank you!

**Comment by zackargyle** [comment]
Published to `@1.3.2`

**Pull request merged**
